"""
tools/side-meta.py — COLLECT THE SLICED SHEETS INTO ONE MODULE.

Reads every `src/assets/side-<breed>.json` that `make-sidesprites.py` wrote and
emits `src/assets/side-meta.js`.

WHY A MODULE AND NOT THE JSON THE GAME FETCHES. These numbers are fixed the
moment a sheet is sliced. Fetching them at runtime would buy a second request, a
second PRECACHE entry and a new failure mode, for values that can simply be code.

Separate from the slicer on purpose: the slicer does one breed, this collects all
of them, and neither can delete the other's work by running.

Usage:  py tools/side-meta.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "src" / "assets"
SHEETMETA = ROOT / "tools" / "sidesheets"

HEADER = '''/* ==========================================================================
   assets/side-meta.js — WHERE THE PROFILE SPRITES ARE, AND HOW BIG.

   GENERATED by tools/side-meta.py from the sheets tools/make-sidesprites.py
   slices. Do not hand-edit — re-slice and re-run.

   The art is the human's own: he drew the profile dog rather than accept the
   drawn one ("i built the side view of the schnoodle with chatgpt as yours looked
   bad"), so `docs/reference/side-walk-*.png` are assets, not references.

   `cellW`/`cellH` are one sprite cell in image pixels. `ground` is the y inside a
   cell that every dog's paws stand on, and `centre` the x his body is centred on.
   Both are identical in every cell BY CONSTRUCTION: the frames are aligned on the
   ground line and the body centre rather than trimmed to their own boxes, because
   a walking leg reaches further than a standing one and trimming each frame would
   make him bob and slide as the cycle ran.

   A BREED WITH NO ENTRY HAS NO SHEET. `dog/sidesprite.js` reports that rather
   than guessing, and the drawn profile (`dog/side.js`) is the fallback — which is
   why that file was kept after the sprites arrived.
   ========================================================================== */
'''


def main():
    rows = []
    for f in sorted(SHEETMETA.glob("side-*.json")):
        m = json.loads(f.read_text(encoding="utf-8"))
        # THE FILENAME COMES FROM THE DISK, not from the JSON. The slicer writes
        # its metadata before it decides between webp and png, so `file` may be
        # absent; and what actually matters is which sheet is really there.
        breed = m["breed"]
        img = next((n for n in ("webp", "png")
                    if (ASSETS / ("side-%s.%s" % (breed, n))).exists()), None)
        if not img:
            print("   skipping %s: metadata but no sheet on disk" % breed)
            continue
        rows.append("  %s: { file: '%s', frames: %d, cellW: %g, cellH: %g,"
                    " ground: %g, centre: %g }," % (
                        breed, "side-%s.%s" % (breed, img), m["frames"],
                        m["cellW"], m["cellH"], m["ground"], m["centre"]))
    out = HEADER + "export const SIDE_SPRITES = {\n" + "\n".join(rows) + \
        "\n};\n\nexport default SIDE_SPRITES;\n"
    (ASSETS / "side-meta.js").write_text(out, encoding="utf-8")
    print("src/assets/side-meta.js — %d breed(s):" % len(rows))
    for r in rows:
        print("   ", r.strip().rstrip(","))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
